name: "test add a tool"
description: "DO NOT USE THIS TEMPLATE"
title: "[addtool] YourToolNiceNameHere"
labels: [
  "bug"
]
body:
  - type: input
    id: link1
    attributes:
      label: "Main link"
      placeholder: "https://..."
    validations:
      required: true
  - type: input
    id: link2
    attributes:
      label: "Link 2"
      placeholder: "https://..."
    validations:
      required: false
  - type: input
    id: link3
    attributes:
      label: "Link 3"
      placeholder: "https://..."
    validations:
      required: false
  - type: input
    id: tags
    attributes:
      label: "Tags"
      description: "tags separated by comma"
      placeholder: "tag1,tag2,tag3..."
    validations:
      required: true
  - type: input
    id: short_descr
    attributes:
      label: "Short description"
      description: "max 100 chars"
      placeholder: "Just another tool for doing things."
    validations:
      required: true
  - type: textarea
    id: long_descr
    attributes:
      label: "Long description"
      description: "No image, only text, Markdown will not be interpreted."
      placeholder: "No image, only text, Markdown will not be interpreted."
    validations:
      required: false
  - type: input
    id: image1
    attributes:
      label: "Main image"
      placeholder: "https://..."
    validations:
      required: true
  - type: input
    id: image2
    attributes:
      label: "Image 2"
      placeholder: "https://..."
    validations:
      required: false
  - type: input
    id: image3
    attributes:
      label: "Image 3"
      placeholder: "https://..."
    validations:
      required: false
  - type: input
    id: image4
    attributes:
      label: "Image 4"
      placeholder: "https://..."
    validations:
      required: false
  - type: input
    id: image5
    attributes:
      label: "Image 5"
      placeholder: "https://..."
    validations:
      required: false
