name: "TEST: Add a tool"
description: "Issue template for easily add a tool on offsec.tools"
title: "[addtool] YourToolNiceNameHere"
labels: [
  "addtool"
]
body:
  - type: input
    id: link1
    attributes:
      label: "Main link"
      placeholder: "https://..."
    validations:
      required: true
  - type: input
    id: link2
    attributes:
      label: "Secondary link"
      placeholder: "https://..."
    validations:
      required: false
  - type: input
    id: link3
    attributes:
      label: "Another link"
      placeholder: "https://..."
    validations:
      required: false
  - type: input
    id: tags
    attributes:
      label: "Tags"
      description: "tags separated by comma"
      placeholder: "tag1,tag2,tag3..."
    validations:
      required: true
  - type: input
    id: short_descr
    attributes:
      label: "Short description"
      placeholder: "Just another tool for doing things."
    validations:
      required: true
  - type: textarea
    id: long_descr
    attributes:
      label: "Long description"
      placeholder: "blablabla"
    validations:
      required: false
  - type: textarea
    id: images
    attributes:
      label: "Image(s)"
      placeholder: |
        https://...
        https://...
        https://...
        https://...
    validations:
      required: true